name: Rain nudger

on:
  schedule:
    - cron: "0 11 * * *"  # runs daily at 11:00 UTC
    - cron: "0 12 * * *"  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run rain check
        run: python rain.py
        env:
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
          CITY: ${{ secrets.CITY }}
          NOTIFY: ${{ secrets.NOTIFY }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TIMEZONE: America/New_York
          HOURS_AHEAD: ${{ vars.HOURS_AHEAD }}
          THRESHOLD: ${{ vars.THRESHOLD }}
          INCLUDE_SUMMARY: "true"
          WEEKDAYS_ONLY: "false"
